//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetExample.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VetExample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrowhead_01 {
            get {
                object obj = ResourceManager.GetObject("Arrowhead-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrowhead_Down_01 {
            get {
                object obj = ResourceManager.GetObject("Arrowhead-Down-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrowhead_Left {
            get {
                object obj = ResourceManager.GetObject("Arrowhead-Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrowhead_Right {
            get {
                object obj = ResourceManager.GetObject("Arrowhead-Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Caduceus {
            get {
                object obj = ResourceManager.GetObject("Caduceus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Command_Refresh_1_ {
            get {
                object obj = ResourceManager.GetObject("Command-Refresh(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Command_Undo {
            get {
                object obj = ResourceManager.GetObject("Command-Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Command_Undo_1_ {
            get {
                object obj = ResourceManager.GetObject("Command-Undo(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dog {
            get {
                object obj = ResourceManager.GetObject("Dog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Item_New {
            get {
                object obj = ResourceManager.GetObject("Item-New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select {0} to be deleted.
        /// </summary>
        internal static string MustSelectToDelete {
            get {
                return ResourceManager.GetString("MustSelectToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select {0} to be restoreded.
        /// </summary>
        internal static string MustSelectToRestore {
            get {
                return ResourceManager.GetString("MustSelectToRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properly saved.
        /// </summary>
        internal static string ProperlySaved {
            get {
                return ResourceManager.GetString("ProperlySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel operation?.
        /// </summary>
        internal static string QCancelOperation {
            get {
                return ResourceManager.GetString("QCancelOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Recover_Deleted_Items {
            get {
                object obj = ResourceManager.GetObject("Recover-Deleted Items", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Report_Delete {
            get {
                object obj = ResourceManager.GetObject("Report-Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save1 {
            get {
                object obj = ResourceManager.GetObject("Save1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On saving errors.
        /// </summary>
        internal static string SavingErrors {
            get {
                return ResourceManager.GetString("SavingErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully deleted.
        /// </summary>
        internal static string SuccessfullyDeleted {
            get {
                return ResourceManager.GetString("SuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully restored.
        /// </summary>
        internal static string SuccessfullyRestored {
            get {
                return ResourceManager.GetString("SuccessfullyRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure you want to delete {0} {1} ?.
        /// </summary>
        internal static string SureToDelete {
            get {
                return ResourceManager.GetString("SureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure you want to restore {0} {1} ?.
        /// </summary>
        internal static string SureToRestore {
            get {
                return ResourceManager.GetString("SureToRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no {0}.
        /// </summary>
        internal static string TheresNo {
            get {
                return ResourceManager.GetString("TheresNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: {0} not deleted.
        /// </summary>
        internal static string WarningNotDeleted {
            get {
                return ResourceManager.GetString("WarningNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: {0} not restored.
        /// </summary>
        internal static string WarningNotRestored {
            get {
                return ResourceManager.GetString("WarningNotRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING - Data Deleting.
        /// </summary>
        internal static string WorningDataDeleting {
            get {
                return ResourceManager.GetString("WorningDataDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING - Data Restoring.
        /// </summary>
        internal static string WorningDataRestoring {
            get {
                return ResourceManager.GetString("WorningDataRestoring", resourceCulture);
            }
        }
    }
}
